### ISSUE TITLE
Ukol 2

### ISSUE THREAD

**Issue by denisakrup** [denisakrup/Ukol2#1]
Ahoj, prosím o kontrolu úkolu 2. 

Nefunguje mi 
1) vypíše mi to pouze jméno společnosti a na adresu mi to vyhodí None,
2) a na výpis právní formy, mi to hází šílenej řetězec. :D

Děkuju a omlouvám se, že to odevzdávám až teď. 

Denisa

**Comment by InsertUsernameH3re** [comment]
```python
adresa_sidla = data.get("textovaAdresa") # <-- textovaAdresa je totiž zanořená v položce sidlo, takže musíš udělat `adresa_sidla = data.get("sidlo").get("textovaAdresa")`
```

Kromě tohohle všechno v pořádku. Právní forma výpis je v pohodě. Chválím. Dodělej tuto drobnost a budeš mít splněné :)

**Comment by InsertUsernameH3re** [comment]
Splněno :)
